### PR TITLE
fix: PZ-3140 - refresh document list after unlinking

### PR DESCRIPTION
**Pull request by infonl-marcel**
Refresh document list after unlinking and a minor aligning center issue when no data available

Resolves: PZ-3140

### CODE REVIEW

**Comment by infonl-marcel** [comment]
This Spotless HTML is way too much in the way; a unexplainable build failure, especially after running the SpotlessApply before committing. And when now running the Apply again there are no changes.

I think we need to have a proper look at that @hsiliev . Maybe there is a different setting for the build itself.

**Comment by hsiliev** [comment]
> This Spotless HTML is way too much in the way; a unexplainable build failure, especially after running the SpotlessApply before committing. And when now running the Apply again there are no changes.
> 
> I think we need to have a proper look at that @hsiliev . Maybe there is a different setting for the build itself.

Tried this out on my machine and I can see exactly the same error as the build reported. I'm doing:
```
./gradlew spotlessCheck 
# errors for src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html

./gradlew spotlessApply
# fixes src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html

./gradlew spotlessCheck
# success
```

Can it be that you still have `zaak-documenten.component.html` on your machine that's not part of the last commit?
Of course, it's also possible spotless+prettier do not work on your setup as expected.

**Comment by hsiliev** [comment]
Resolved the conflicts and pushed Spotless formatting

**Review by edgarvonk — APPROVED** [review]
nice one

**Pull request merged**
